spring:
  application:
    name: ebenezer-service

  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8085



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
