spring:
  application:
    name: ebenezer-weather-service
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false

server:
  port: 8085

openWeather:
  baseUrl: https://api.openweather.org/data/2.5/weather

app:
  id: ${appid}
