weather:
  url: https://weather-by-api-ninjas.p.rapidapi.com/v1/weather
  apikey: ${api_key}
  apiHost: X-RapidAPI-Key

server:
  port: 8070
spring:
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
