weather:
  url: https://weather-by-api-ninjas.p.rapidapi.com/v1/weather
  apikey: 5d13c40123msh0c52c6c68b09423p15eb89jsnf45cdb709bbd
  apiHost: X-RapidAPI-Key

server:
  port: 8070
spring:
  cloud:
    config:
      enabled: false
  application:
    name: samuel-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/